### PR TITLE
Initial stab at Django 1.8 suport

### PR DESCRIPTION
**Pull request by sgithens**
This is an initial stab at supporting Django 1.8, may require some changes for cleanliness.  On my local machine all the unit tests are passing (except the reddis ones I still haven't set up)

One thing I have NOT done yet on this branch, is delete/remove the directory of South migrations and use the newer django makemigrations command to generate Django 1.8 migrations.  I'm still unsure of the smoothest way of transitioning projects from south to migrations (other than just deleting the South migrations wholesale, and generating new ones from scratch).

### CODE REVIEW

**Comment by bruth** [comment]
Thanks Steven. The Python 2.6 failures are due to the set literal syntax e.g. `{1, 2, 3}`. Let's drop Python 2.6 from the `.travis.yml` config. The remaining error is a model tree one. I just pushed modeltree 2.0.0 to PyPi which has Django 1.8 and 1.9 support and drops previous versions. Try updating the requirements to depend on 2.0.0 and see what happens.

**Comment by sgithens** [comment]
Thanks! Will make those config/dep changes shortly and try pushing them up.

**Comment by sgithens** [comment]
Awesome, it looks like things passed.  If you want to give an initial review of the changes that would be great.  I (or someone) still needs to look the accepted South->Migrations strategy.

Also, it appears that it's pretty hard to support django 1.8 and previous django versions, so I'm not sure if you'd to create maintenance branches for previous django versions, or not worry about it.

**Comment by bruth** [comment]
This is great. Can you update the `.travis.yml` to include Django 1.8.x so the tests run against that version.

**Pull request merged**
