### PR TITLE
README was pointing to cilantro contributing instead of avocado

### PR DESCRIPTION
**Pull request by sgithens**
Minor link change to avocado repo instead of cilantro for the contributing agreement.

### CODE REVIEW

**Comment by aaron0browne** [comment]
Thanks for this, @sgithens! Ironically, the tests are failing because your commits are not "signed off", as the contributing guide requires 😄 . Can you amend your commits with sign-offs?

**Comment by sgithens** [comment]
@aaron0browne Hahahaha, I figured that might happen from reading contributor guide... expect that I couldn't tell from from the document how you actually sign off on a commit.  Is it based on metadata or tags that you add to a git commit message, or to the github message in the pull request, or something else?

**Comment by sgithens** [comment]
Ok, so do you just physically put this in every commit message?
```
This is my commit message... is there a newline required before the signoff syntax?
Signed-off-by: Steven Githens <swgithen@mtu.edu>
```

**Comment by bruth** [comment]
@sgithens Thanks Steven. Adding the `-s` flag to `git commit` will add the `Signed-off-by:` line for you. Yes it should be on every commit.

**Comment by bruth** [comment]
A quick fix would be to run `git rebase -i master` and mark each commit with `e` for edit. Git stop on each commit allowing you to edit the commit. Simply run `git commit -s` and it will augment the signature.

**Comment by sgithens** [comment]
@bruth Thanks for the switches! Should be fixed up now.

**Comment by bruth** [comment]
Thanks!

**Pull request merged**
