### PR TITLE
Modify *get_result_rows to accept kwargs for QueryProcessor

### PR DESCRIPTION
**Pull request by murphyke**
See https://github.com/chop-dbhi/serrano/issues/295.  When using a custom QueryProcessor to modify queries based on contents of the `request` object, such as `user` or `session`, something like this patch may be required.

### CODE REVIEW

**Comment by murphyke** [comment]
OK; will sign the commit.

**Comment by murphyke** [comment]
I see from Byron's comment at https://github.com/chop-dbhi/serrano/issues/295#issuecomment-241092906 that this won't work for the async calls.

**Comment by bruth** [comment]
Well to be clear, this change does not actually result in the breakage. It still requires the request itself to be passed in by Serrano. Grant it, this is an implicit contract..

**Comment by murphyke** [comment]
Yes, I meant "won't work when used as I intended".

**Comment by bruth** [comment]
Good idea.. I am taking a look.

**Comment by bruth** [comment]
Wrong thread..

**Pull request closed without merging**
